### ISSUE TITLE
Doesnt work after installing

### ISSUE THREAD

**Issue by barikasss** [Tagirijus/kanboard-TagiTaskAutoColor#1] opened 2023-10-31 10:03 UTC
![image](https://github.com/Tagirijus/TaskAutoColor/assets/69697069/38fba6ed-78b6-4675-88a2-02eaacdefcd3)

Hello ! 
I install your plugin, but he goes to list "Incompatible Plugins", what i should to do?

**Comment by Tagirijus** [comment] 2023-10-31 10:06
Did you install it via Github clone command, like mentioned in the README?

Also: you might want to check out another plugin I basically moved this plugin into yesterday:

https://github.com/Tagirijus/TagiAutoActions

**Comment by Tagirijus** [comment] 2023-11-01 14:01
Feel free to provide further information. In the meantime I will close this issue. I will re-open it (or I think you might be able to), if I can reproduce your issue. Thanks!

**Closed as completed by Tagirijus** 2023-11-01 14:01 UTC
Labels: invalid

**Comment by barikasss** [comment] 2023-11-02 12:47
Sorry, my kanboard was old, thank you for this plugin, i already install newest version :)
![image](https://github.com/Tagirijus/TaskAutoColor/assets/69697069/e5860e44-4820-4794-b9a1-45398654e984)

**Comment by Tagirijus** [comment] 2023-11-02 12:51
Nice! I am glad it works for you now. Still you might want to check out [the other plugin](https://github.com/Tagirijus/TagiAutoActions), since I won't update this plugin anymore.

The difference in the other plugin so far: you have to set it up as an automatic action per project (thus you do not have to have this feature in every project) and you can also define your own colors in the configs with the new plugin.
